[run]
command:/usr/local/opnsense/scripts/OPNsense/Fleet/agent.py run
parameters:
type:script_output
message:os-fleet-agent: send status to server
description:os-fleet-agent run

[test]
command:/usr/local/opnsense/scripts/OPNsense/Fleet/agent.py test
parameters:
type:script_output
message:os-fleet-agent: probe server connection
description:os-fleet-agent test

[setup]
command:/usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/Fleet/cron_setup.php
parameters:
type:script_output
message:os-fleet-agent: register cron job
description:os-fleet-agent setup
